import type { LucideIcon } from "lucide-react";
import {
  Pipette,
  Palette,
  Layers,
  Type,
  LayoutGrid,
  Shapes,
  Binary,
  ShieldCheck,
  Link2,
  Languages,
  FileText,
  ImageIcon,
  Music,
  Film,
  Baseline,
  FileOutput,
  FileKey2,
  Code2,
  Hash,
  Contrast,
  Search,
  Gauge,
  Cookie,
  MonitorSmartphone,
  Share2,
  Bot,
  Network,
  QrCode,
  FileJson,
  TableProperties,
  Fingerprint,
  Database,
  Clock,
  Wifi,
  Coffee,
  Braces,
  Regex,
  Table2,
  GitCompare,
  BookOpen,
  Send,
  Bookmark,
  ScanText,
  Ruler,
  TrendingUp,
  DollarSign,
} from "lucide-react";

export interface ToolItem {
  id: string;
  label: string;
  description: string;
  href: string;
  icon: LucideIcon;
  badge?: "NEW" | "인기";
}

export const CODE_TOOLS: ToolItem[] = [
  {
    id: "json-formatter",
    label: "JSON Formatter / Validator",
    description: "JSON 포맷 정렬 · 최소화 · 유효성 검사 및 오류 위치 표시",
    href: "/tools/code/json-formatter",
    icon: Braces,
    badge: "NEW",
  },
  {
    id: "regex-tester",
    label: "Regex Tester",
    description: "정규식 패턴 테스트 · 매치 그룹 시각화 · 플래그 옵션 지원",
    href: "/tools/code/regex-tester",
    icon: Regex,
    badge: "NEW",
  },
  {
    id: "sql-formatter",
    label: "SQL Formatter",
    description: "SQL 쿼리 자동 정렬 · 키워드 대문자 변환 · 복사",
    href: "/tools/code/sql-formatter",
    icon: Table2,
    badge: "NEW",
  },
  {
    id: "diff-tool",
    label: "Diff / Merge Tool",
    description: "두 텍스트 라인 단위 비교 · 추가/삭제 하이라이트 시각화",
    href: "/tools/code/diff-tool",
    icon: GitCompare,
    badge: "NEW",
  },
  {
    id: "markdown-editor",
    label: "Markdown Editor",
    description: "마크다운 실시간 미리보기 · 편집기 분할 화면",
    href: "/tools/code/markdown-editor",
    icon: BookOpen,
    badge: "NEW",
  },
  {
    id: "api-tester",
    label: "API Request Tester",
    description: "HTTP 요청 전송 · 응답 확인 · 헤더 / 바디 설정",
    href: "/tools/code/api-tester",
    icon: Send,
    badge: "NEW",
  },
  {
    id: "snippet-manager",
    label: "Code Snippet Manager",
    description: "코드 스니펫 저장 · 검색 · 복사 (로컬 저장소 기반)",
    href: "/tools/code/snippet-manager",
    icon: Bookmark,
    badge: "NEW",
  },
  {
    id: "lint-analyzer",
    label: "Lint / Static Analyzer",
    description: "JS·TS·Python·HTML·CSS 기본 코드 품질 검사 및 이슈 리포트",
    href: "/tools/code/lint-analyzer",
    icon: ScanText,
    badge: "NEW",
  },
];

export const DESIGN_TOOLS: ToolItem[] = [
  {
    id: "icon-library",
    label: "아이콘 라이브러리",
    description: "무료 SVG 아이콘 검색 및 React / SVG 코드 복사",
    href: "/tools/design/icon-library",
    icon: Shapes,
  },
  {
    id: "font-preview",
    label: "폰트 미리보기",
    description: "다양한 웹폰트 조합 및 스타일 시각화",
    href: "/tools/design/font-preview",
    icon: Type,
  },
  {
    id: "grid-generator",
    label: "그리드 / 레이아웃 생성기",
    description: "CSS Flexbox / Grid 코드 자동 생성",
    href: "/tools/design/grid-generator",
    icon: LayoutGrid,
  },
  {
    id: "color-picker",
    label: "Color Picker",
    description: "HEX ↔ RGB ↔ HSL 변환 및 색상 시각화",
    href: "/tools/design/color-picker",
    icon: Pipette,
  },
  {
    id: "color-palette",
    label: "Color Palette Generator",
    description: "입력 색상 기반 보색·유사색·삼색 팔레트 생성",
    href: "/tools/design/color-palette",
    icon: Palette,
  },
  {
    id: "gradient-generator",
    label: "Gradient / CSS Generator",
    description: "색상 조합으로 그라데이션 CSS 코드 즉시 생성",
    href: "/tools/design/gradient-generator",
    icon: Layers,
  },
];

export const ENCODE_DECODE_TOOLS: ToolItem[] = [
  {
    id: "base-encoder",
    label: "Base 인코더 / 디코더",
    description: "Base32 · Base58 · Base64 인코딩 및 디코딩",
    href: "/tools/encode-decode/base-encoder",
    icon: Binary,
  },
  {
    id: "crypto-tool",
    label: "암호화 / 복호화",
    description: "AES-256 대칭 암호화 · RSA-2048 비대칭 암호화 테스트",
    href: "/tools/encode-decode/crypto-tool",
    icon: ShieldCheck,
  },
  {
    id: "url-shortener",
    label: "URL 단축기",
    description: "긴 URL을 짧은 링크로 즉시 변환",
    href: "/tools/encode-decode/url-shortener",
    icon: Link2,
  },
  {
    id: "jwt-decoder",
    label: "JWT 디코더",
    description: "JWT 토큰의 Header · Payload · 만료 시간을 브라우저에서 즉시 디코딩",
    href: "/tools/encode-decode/jwt-decoder",
    icon: FileKey2,
  },
  {
    id: "html-encoder",
    label: "HTML 인코더 / 디코더",
    description: "특수 문자 ↔ HTML 엔티티(&amp; &lt; &gt; &quot;) 양방향 변환",
    href: "/tools/encode-decode/html-encoder",
    icon: Code2,
  },
  {
    id: "sha256",
    label: "Hash 생성기",
    description: "SHA-256 · SHA-1 · SHA-512 해시를 HEX · Base64로 즉시 계산",
    href: "/tools/encode-decode/sha256",
    icon: Hash,
  },
];

export const TEXT_TOOLS: ToolItem[] = [
  {
    id: "lang-detector",
    label: "언어 감지 / 번역",
    description: "텍스트 언어 자동 감지 및 10개 언어 번역",
    href: "/tools/text/lang-detector",
    icon: Languages,
  },
  {
    id: "summarizer",
    label: "문장 요약 / 키워드 추출",
    description: "긴 글에서 핵심 문장과 주요 키워드 자동 추출",
    href: "/tools/text/summarizer",
    icon: FileText,
  },
  {
    id: "alt-text",
    label: "대체 텍스트 생성기",
    description: "이미지 설명용 alt 텍스트 작성 가이드 및 접근성 향상",
    href: "/tools/text/alt-text",
    icon: ImageIcon,
  },
  {
    id: "word-counter",
    label: "Word Counter",
    description: "글자 수·단어 수·문장 수·읽기 시간 분석 및 키워드 빈도 통계",
    href: "/tools/text/word-counter",
    icon: Hash,
    badge: "NEW",
  },
  {
    id: "case-converter",
    label: "Case Converter",
    description: "camelCase · snake_case · PascalCase · kebab-case · UPPER / lower 즉시 변환",
    href: "/tools/text/case-converter",
    icon: Code2,
    badge: "NEW",
  },
  {
    id: "slug-generator",
    label: "Slug Generator",
    description: "제목 또는 문장을 URL 친화적인 slug로 즉시 변환",
    href: "/tools/text/slug-generator",
    icon: Link2,
    badge: "NEW",
  },
  {
    id: "lorem-ipsum",
    label: "Lorem Ipsum Generator",
    description: "단락·단어·문장 단위로 Lorem Ipsum 더미 텍스트 생성",
    href: "/tools/text/lorem-ipsum",
    icon: FileText,
    badge: "NEW",
  },
];

export const CONVERTER_TOOLS: ToolItem[] = [
  {
    id: "audio-converter",
    label: "오디오 변환기",
    description: "MP3·WAV·OGG 등 오디오를 WAV로 변환 및 미리보기",
    href: "/tools/converter/audio-converter",
    icon: Music,
  },
  {
    id: "video-converter",
    label: "비디오 압축기",
    description: "MP4·WebM 해상도·화질 압축 및 WebM 포맷 변환",
    href: "/tools/converter/video-converter",
    icon: Film,
  },
  {
    id: "font-converter",
    label: "폰트 변환기",
    description: "TTF·OTF → WOFF 변환 및 CSS @font-face 코드 생성",
    href: "/tools/converter/font-converter",
    icon: Baseline,
  },
  {
    id: "doc-converter",
    label: "문서 변환기",
    description: "이미지 → PDF 변환 및 PDF → 이미지 추출",
    href: "/tools/converter/doc-converter",
    icon: FileOutput,
  },
  {
    id: "image-converter",
    label: "이미지 변환기",
    description: "JPEG·PNG·WebP·SVG 포맷 변환, 압축, 리사이즈, 배경 제거",
    href: "/tools/converter/image-converter",
    icon: ImageIcon,
  },
  {
    id: "qr-tool",
    label: "QR 코드 도구",
    description: "URL → QR 코드 생성 및 QR 이미지/카메라 스캔으로 정보 추출",
    href: "/tools/converter/qr-tool",
    icon: QrCode,
    badge: "NEW",
  },
];

export const WEB_TOOLS: ToolItem[] = [
  {
    id: "color-contrast",
    label: "Color Contrast Checker",
    description: "전경색·배경색 조합의 WCAG AA · AAA 명암비 즉시 검사",
    href: "/tools/web/color-contrast",
    icon: Contrast,
    badge: "NEW",
  },
  {
    id: "seo-analyzer",
    label: "SEO 분석기",
    description: "title · description · heading · OpenGraph 태그 분석 및 점수 산출",
    href: "/tools/web/seo-analyzer",
    icon: Search,
  },
  {
    id: "performance-test",
    label: "Performance Test",
    description: "PageSpeed Insights로 Core Web Vitals 측정",
    href: "/tools/web/performance-test",
    icon: Gauge,
  },
  {
    id: "cookie-viewer",
    label: "Cookie / Session Viewer",
    description: "현재 페이지의 Cookie · localStorage · sessionStorage 조회",
    href: "/tools/web/cookie-viewer",
    icon: Cookie,
  },
  {
    id: "meta-preview",
    label: "Meta Tag Preview",
    description: "Google 검색 결과 스니펫 미리보기",
    href: "/tools/web/meta-preview",
    icon: MonitorSmartphone,
  },
  {
    id: "og-preview",
    label: "OpenGraph Preview",
    description: "Facebook · Twitter(X) · Discord 소셜 카드 미리보기",
    href: "/tools/web/og-preview",
    icon: Share2,
  },
  {
    id: "robots-generator",
    label: "Robots.txt Generator",
    description: "User-agent 규칙으로 robots.txt 즉시 생성",
    href: "/tools/web/robots-generator",
    icon: Bot,
  },
  {
    id: "sitemap-generator",
    label: "Sitemap Generator",
    description: "URL 목록을 XML sitemap으로 즉시 변환",
    href: "/tools/web/sitemap-generator",
    icon: Network,
  },
];

export const DATA_FORMAT_TOOLS: ToolItem[] = [
  {
    id: "csv-json",
    label: "CSV ↔ JSON",
    description: "CSV와 JSON 형식을 양방향으로 즉시 변환",
    href: "/tools/data-format/csv-json",
    icon: FileJson,
    badge: "NEW",
  },
  {
    id: "excel-converter",
    label: "Excel 변환기",
    description: "XLSX·XLS·CSV 파일을 JSON 또는 CSV로 변환 및 테이블 미리보기",
    href: "/tools/data-format/excel-converter",
    icon: TableProperties,
    badge: "NEW",
  },
  {
    id: "uuid-generator",
    label: "UUID 생성기",
    description: "UUID v4 단일·대량 생성 및 다양한 포맷 변환",
    href: "/tools/data-format/uuid-generator",
    icon: Fingerprint,
    badge: "NEW",
  },
  {
    id: "data-generator",
    label: "샘플 데이터 생성기",
    description: "이름·이메일·전화번호 등 테스트용 샘플 데이터를 JSON·CSV·SQL로 즉시 생성",
    href: "/tools/data-format/data-generator",
    icon: Database,
    badge: "NEW",
  },
  {
    id: "timestamp-converter",
    label: "타임스탬프 변환기",
    description: "Unix 타임스탬프 ↔ 날짜/시간 양방향 변환 및 KST·UTC 동시 표시",
    href: "/tools/data-format/timestamp-converter",
    icon: Clock,
    badge: "NEW",
  },
];

export const JOBS_TOOLS: ToolItem[] = [
  {
    id: "area-calculator",
    label: "평수 계산기",
    description: "평 ↔ m² ↔ ft² 면적 단위 변환 · 전용·공급·계약면적 계산",
    href: "/tools/jobs/area-calculator",
    icon: Ruler,
    badge: "NEW",
  },
];

export const ETC_TOOLS: ToolItem[] = [
  {
    id: "crypto-tracker",
    label: "암호화폐 시세",
    description: "상위 50개 코인 실시간 시세 · 가격 차트 · 검색 (60초 자동 갱신)",
    href: "/tools/etc/crypto-tracker",
    icon: TrendingUp,
    badge: "NEW",
  },
  {
    id: "currency-converter",
    label: "환율 변환기",
    description: "160개 통화 환율 조회 및 변환 · 일 1회 업데이트",
    href: "/tools/etc/currency-converter",
    icon: DollarSign,
    badge: "NEW",
  },
  {
    id: "ip-lookup",
    label: "공인 IP 조회",
    description: "현재 접속 중인 공인 IP 주소 및 위치 정보 즉시 조회",
    href: "/tools/etc/ip-lookup",
    icon: Wifi,
    badge: "NEW",
  },
  {
    id: "coffee-bet",
    label: "커피내기 컬렉션",
    description: "팀원과 커피 내기를 할 수 있는 다양한 미니 게임 모음",
    href: "/tools/etc/coffee-bet",
    icon: Coffee,
    badge: "NEW",
  },
];

/** 카테고리 ID → 도구 목록 맵 */
export const TOOLS_BY_CATEGORY: Record<string, ToolItem[]> = {
  code: CODE_TOOLS,
  design: DESIGN_TOOLS,
  "encode-decode": ENCODE_DECODE_TOOLS,
  text: TEXT_TOOLS,
  converter: CONVERTER_TOOLS,
  web: WEB_TOOLS,
  "data-format": DATA_FORMAT_TOOLS,
  jobs: JOBS_TOOLS,
  etc: ETC_TOOLS,
};